### ISSUE TITLE
how to change top bar background?

### ISSUE THREAD

**Issue by NilTPL** [mgastonportillo/gale-for-ff#2]
Hi! - love how the theme looks, but was interested in changing the background of the top bar to be the same one that's included with [the Dark Trans Pride Theme ](https://addons.mozilla.org/en-US/firefox/addon/dark-trans-pride-theme/) from the firefox theme store. would you happen to know how i could be able to find a way of extracting the background from that theme to replace in this one? and if so, would you tell me how to replace it in the userchome.css file?

changing the button colors might be simple enough but im not sure about the background, since it's probably an image file and not just a hex code.

**Comment by mgastonportillo** [comment]
Hey there NilTPL, I created a css background version of the flag which you can add to the element you want. I chose not to implement it myself as it looks ugly when put directly on the top bar, and you can definitely implement it in a way that actually works for you. Here's the css:
```css
background: linear-gradient(120deg, #2b2a33 0%, #2b2a33 87.5%, #7ccbf4 87.5%, #7ccbf4 90%, #e9abb6 90%, #e9abb6 92.5%, #ffffff 92.5%, #ffffff 95%, #e9abb6 95%, #e9abb6 97.5%, #7ccbf4 97.5%, #7ccbf4 100%);
```
You can adapt the flag size by modifying the colours percentages (in pairs) and its angle by modifying the first value (120deg). You can also remove the black that pushes the flag to the right by removing the two instances of `#2b2a33`.

Good luck!
