### ISSUE TITLE
Not auto-hiding/auto-suggestions from address bar overlap

### ISSUE THREAD

**Issue by jontstaz** [mgastonportillo/gale-for-ff#5]
I can't imagine this is the expected behaviour. Have I done something wrong? I followed the instructions exactly 1:1 so not sure what it could be.. Thanks in advance for any suggestions. (My screenshot tool auto-hides the address drop-down.)
![image](https://github.com/mgastonportillo/gale-for-ff/assets/6379873/13e2c824-6896-448d-ab16-ae130a3a6b24)

**Comment by mgastonportillo** [comment]
Are you using Sidebery v5 beta with the latest release of my theme? Because I can't guarantee that it will work with Sidebery v4. The screenshot you sent doesn't have Sidebery with my theme. To me, it seems that you haven't applied the Sidebery css styles at all.

**Comment by jontstaz** [comment]
Ahh I see, I had v4 stable installed as it wasn't clear before that I had to use v5 beta. Seems all good now except it doesn't disappear on hover. Not sure if it's meant to disappear on hover but it would be super nice if it did

**Comment by mgastonportillo** [comment]
Awesome! And that feature has been disabled due to a bug present in v5. Once it gets fixed, I'll bring it back.

**Comment by mgastonportillo** [comment]
You can use the [legacy](https://github.com/mgastonportillo/gale-for-ff/tree/main/legacy) version of the theme alongside Sidebery v4 if you want the original experience

**Comment by emiham** [comment]
This is a Firefox bug on Linux, here is the relevant Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1818517

There is a fix in that thread: setting `widget.gtk.ignore-bogus-leave-notify` to `1` in `about:config` seems to solve it, but no guarantees on what else that affects.

**Comment by mgastonportillo** [comment]
@emiham you know, that explains another weird behaviour I was experiencing in a different project. Thanks for the heads-up. I'll investigate, as it's mentioned to happen under Gnome (my choice) but Wayland seems fine.
