### ISSUE TITLE
Unable to resize sidebar

### ISSUE THREAD

**Issue by cosmojg** [mgastonportillo/gale-for-ff#7]
When using the provided `userChrome.css`, I lose the ability to resize my sidebar using the mouse.

**Comment by mgastonportillo** [comment]
@cosmojg are you using the legacy version by any chance? That's intended. For the newest release, it should be working.

**Comment by mgastonportillo** [comment]
If you're having any issues with Sidebery, always try the combination `CTRL + E` to close it, and then repeat it to re-open it. Might be of help in many cases.

**Comment by mgastonportillo** [comment]
In case you're wondering, I didn't like the original looks (I know it's for the sake of accessibility, but my theme's focus isn't accessibility) of what Firefox calls a sidebar splitter, so I tweaked it a bit to make it resemble the border of the sidebar in my theme. So it seems to be gone, but functionality wise it's present.

**Comment by cosmojg** [comment]
Yeah, I'm using the latest commit on main. If it helps, I'm running Firefox 118 on macOS Sonoma. Here's a screencast:

https://github.com/mgastonportillo/gale-for-ff/assets/19784632/c9b4edfd-85f9-4000-8223-f56456d99b86

**Comment by mgastonportillo** [comment]
Comment this out in your `userChrome.css`:
```css
#sidebar-splitter {
	width: 0px !important;
	border: 2px solid var(--gg-bg) !important;
}
```
That's all I changed regarding that functionality. Right now I'm writing this with that change applied, as you can see in the screenshot I attached. If that doesn't bring back the functionality, then check if you applied any changes yourself, something could be causing a conflict. The border css property should work in macOS.

![image](https://github.com/mgastonportillo/gale-for-ff/assets/106234166/e4e71590-39fa-4212-9980-ba9c1b554d9a)

**Comment by cosmojg** [comment]
Nope, that didn't fix it either. Your CSS files are the only ones I'm using, and I haven't made any changes. Weird! I'll try to do some more debugging on my own when I have the time.

**Comment by mgastonportillo** [comment]
I'll push an update in a minute making sure the right changes are in the repo. Hopefully it's just a mistake on my side.

**Comment by cosmojg** [comment]
Good news! I was able to fix it by deleting `z-index: 1;` on line 32 of `userChrome.css` in the `#sidebar-box {}` id selector field.

**Comment by mgastonportillo** [comment]
Awesome! I'm glad you were able to sort it out. I'll check it out and apply a fix if necessary. Thanks for the heads-up!

**Comment by mgastonportillo** [comment]
Patch applied
