### ISSUE TITLE
Unable to choose container when opening new tab

### ISSUE THREAD

**Issue by chookity-pokk** [mgastonportillo/gale-for-ff#8]
Without Sideberry I have my setup as when I click on a new tab, I get the prompt asking which container I want to open it in but with this setup (might also be a sideberry problem?), I am unable to open a new tab in anything other than the default container and then I have to right click the tab and reopen in the container I want.

**Comment by mgastonportillo** [comment]
Hello there @chookity-pokk, is this a feature Sidebery offers by default? I don't think I removed any relevant feature from its navbar as of the latest release.

What I do to open new tabs on different containers is right click on the new tab button and then pick the container from the list. All of this is the default behaviour of Sidebery. Same for existing tabs, just right click on them and re-open on the target container.

**Comment by chookity-pokk** [comment]
I think you are right, I think this is more of a Sideberry thing. Sorry for the noise! Though thank you so much for the tip! That solves my problem entirely!
