### ISSUE TITLE
Dark flickers when webpages load when they are forced to use light theme?

### ISSUE THREAD

**Issue by rieje** [mgastonportillo/gale-for-ff#9]
I set `layout.css.prefers-color-scheme.content-override` to `1` to make webpages load light themes (not all webpages support dark and I prefer light for readability). When pages load, the page is black until the page gets loaded. Any ideas on how it would be white (the default) instead?

Also, any ideas on how the search bar's drop down menu can be set to the black? I managed to do this for the drop down of the address bar with `urlbar but not for the search bar. 

Much appreciated.`

**Comment by mgastonportillo** [comment]
Mmm, my dark theme overrides might be the culprit. Try commenting out everything that's under the --gg variables in the 
`darkTheme.css` file and test your workflow.

I don't really plan to support white themes or its features, but this seems like something I should debug, as I understand you want Firefox dark themed but your web content light themed. I'm afraid, though, that I won't be able to provide support for the theme if it's related to breaking changes, as right now I'm using a different main browser and won't have enough time to push updates in a decent time span.

For the search bar, I know that it's possible but I couldn't get a result I liked in the past, when I tried. Try using the remote debugging if you're not using it yet.

Sorry if that's not of much help.

**Comment by rieje** [comment]
I'm able to solve the first issue from the [solution here](https://old.reddit.com/r/firefox/comments/wlvr2m/cant_use_dark_mode_because_of_screen_flashes/ijz7rtn/). Thanks.
